<?php

namespace Application\Bundle\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AcidDetectionStripsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcidDetectionStripsRepository extends EntityRepository
{
    public function getAllAsArray()
    {
        $names = $this->getEntityManager()->createQuery('SELECT distinct(acidDetectionStrips.name)'
                . ' from ApplicationFrontBundle:AcidDetectionStrips  acidDetectionStrips'
                )->getScalarResult();
        $acidDetectionStrips = array_map("current",$names);

        return $acidDetectionStrips;
    }
}
