<?php

namespace Application\Bundle\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AudioRecordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AudioRecordsRepository extends EntityRepository
{

	function findRecrd($recordId)
	{
		$query = $this->getEntityManager()->createQuery('SELECT u FROM ApplicationFrontBundle:AudioRecords u WHERE u.id = ' . $recordId);
		$users = $query->getArrayResult();
	}

}
