<?php

namespace Application\Bundle\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CassetteSizesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CassetteSizesRepository extends EntityRepository
{
    public function getAllAsArray(){
        $names = $this->getEntityManager()->createQuery('SELECT distinct(cassetteSizes.name)'
                . ' from ApplicationFrontBundle:CassetteSizes cassetteSizes'
                )->getScalarResult();
        $cassetteSizes = array_map("current",$names);
        return $cassetteSizes;
    }
}
