<?php

namespace Application\Bundle\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommercialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommercialRepository extends EntityRepository
{
    public function getAllAsArray(){
        $names = $this->getEntityManager()->createQuery('SELECT commercial.name'
                . ' from ApplicationFrontBundle:Commercial commercial'
                )->getScalarResult();
        $commercial = array_map("current",$names);
        return $commercial;
    }
}
