<?php

namespace Application\Bundle\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DiskDiametersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiskDiametersRepository extends EntityRepository
{
    public function getAllAsArray(){
        $names = $this->getEntityManager()->createQuery('SELECT distinct(diskDiameters.name)' 
                . ' from ApplicationFrontBundle:DiskDiameters diskDiameters'
                )->getScalarResult();
        $dd = array_map("current",$names);
        return $dd;
    }
}
