<?php

namespace Application\Bundle\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FormatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormatsRepository extends EntityRepository
{
    public function getAllAsArray()
    {
        $names = $this->getEntityManager()->createQuery('SELECT formats.name'
                . ' from ApplicationFrontBundle:Formats formats'
                )->getScalarResult();
        $formats = array_map("current",$names);

        return $formats;
    }
}
