<?php

namespace Application\Bundle\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FrameRatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrameRatesRepository extends EntityRepository
{
    public function getAllAsArray()
    {
        $names = $this->getEntityManager()->createQuery('SELECT distinct(frameRates.name)'
                . ' from ApplicationFrontBundle:FrameRates frameRates'
                )->getScalarResult();
        $frameRates = array_map("current",$names);

        return $frameRates;
    }
}
