<?php

namespace Application\Bundle\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MediaDiametersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaDiametersRepository extends EntityRepository
{
    public function getAllAsArray()
    {
        $names = $this->getEntityManager()->createQuery('SELECT distinct(mediaDiameters.name)'
                . ' from ApplicationFrontBundle:MediaDiameters mediaDiameters'
                )->getScalarResult();
        $md = array_map("current",$names);

        return $md;
    }
}
