<?php

namespace Application\Bundle\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NoiceReductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoiceReductionRepository extends EntityRepository
{
    public function getAllAsArray(){
        $names = $this->getEntityManager()->createQuery('SELECT distinct(noiceReduction.name)'
                . ' from ApplicationFrontBundle:NoiceReduction noiceReduction'
                )->getScalarResult();
        $nr = array_map("current",$names);
        return $nr;
    }
}
