<?php
/**
 * AVCC
 * 
 * @category AVCC
 * @package  Application
 * @author   Nouman Tayyab <nouman@avpreserve.com>
 * @author   Rimsha Khalid <rimsha@avpreserve.com>
 * @license  AGPLv3 http://www.gnu.org/licenses/agpl-3.0.txt
 * @copyright Audio Visual Preservation Solutions, Inc
 * @link     http://avcc.avpreserve.com
 */
namespace Application\Bundle\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrganizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationRepository extends EntityRepository
{
     public function getAll() {
        $query = $this->getEntityManager()
                ->createQuery("SELECT o.id, o.name, o.departmentName, o.address, o.contactPersonName, o.contactPersonEmail, o.status, o.contactPersonPhone from ApplicationFrontBundle:Organizations o ");
        return $query->getArrayResult();
    }
}
