<?php

namespace Application\Bundle\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrintTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrintTypesRepository extends EntityRepository
{
    public function getAllAsArray()
    {
        $names = $this->getEntityManager()->createQuery('SELECT printTypes.name'
                . ' from ApplicationFrontBundle:PrintTypes printTypes'
                )->getScalarResult();
        $pt = array_map("current",$names);

        return $pt;
    }
}
