<?php

/**
 * AVCC
 * 
 * @category AVCC
 * @package  Application
 * @author   Nouman Tayyab <nouman@avpreserve.com>
 * @author   Rimsha Khalid <rimsha@avpreserve.com>
 * @license  AGPLv3 http://www.gnu.org/licenses/agpl-3.0.txt
 * @copyright Audio Visual Preservation Solutions, Inc
 * @link     http://avcc.avpreserve.com
 */

namespace Application\Bundle\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectsRepository extends EntityRepository {

    public function getAllAsArray() {
        $names = $this->getEntityManager()->createQuery('SELECT projects.name'
                        . ' from ApplicationFrontBundle:Projects projects'
                )->getScalarResult();
        $p = array_map("current", $names);

        return $p;
    }

    public function getFileSizeById($id) {
        $query = $this->getEntityManager()
                ->createQuery('SELECT projects.name,projects.audioFilesize,projects.videoFilesize,projects.filmFilesize'
                . ' from ApplicationFrontBundle:Projects projects '
                . "WHERE projects.id =  :pid");
        $query->setParameter('pid', $id);
        return $query->getSingleResult();
    } 

}
