<?php

namespace Application\Bundle\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * RecordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecordsRepository extends EntityRepository
{

	public function findOrganizationRecords($organizationID)
	{
		$rsm = new ResultSetMapping();
		$query = $this->getEntityManager()->createNativeQuery('SELECT r FROM ApplicationFrontBundle:Records r', $rsm);
//		$query->setParameter(1, 'romanb');

		$users = $query->getResult();
		return $users;
		$result = $this->getEntityManager()->createQuery("SELECT r"
		. " FROM ApplicationFrontBundle:Records r"
		. " JOIN ApplicationFrontBundle:MediaTypes m WITH r.mediaType = m.id"
		. " JOIN ApplicationFrontBundle:Projects p WITH r.project = p.id"
		. " order by r.id $order"
		)
//                        ->setMaxResults($limit)
//                        ->setFirstResult($offSet)
		->getArrayResult();

		return $result;
	}

	public function findAudioRecordById($id)
	{
		return $this->getEntityManager()->createQuery("SELECT r as record, ar as audio, m.name as mediaType, p.name as projectTitle"
		. " FROM ApplicationFrontBundle:Records r"
		. " JOIN ApplicationFrontBundle:MediaTypes m WITH r.mediaType = m.id"
		. " JOIN ApplicationFrontBundle:Projects p WITH r.project = p.id"
		. " JOIN ApplicationFrontBundle:AudioRecords ar WITH ar.record = r.id "
		. " Where r.id = $id"
		)
		->getArrayResult();
	}

}
