<?php

namespace Application\Bundle\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecordingStandardsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecordingStandardsRepository extends EntityRepository
{
    public function getAllAsArray(){
        $names = $this->getEntityManager()->createQuery('SELECT distinct(recordingStandards.name)'
                . ' from ApplicationFrontBundle:RecordingStandards recordingStandards'
                )->getScalarResult();
        $rs = array_map("current",$names);
        return $rs;
    }
}
