<?php

namespace Application\Bundle\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReelCoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReelCoreRepository extends EntityRepository
{
    public function getAllAsArray()
    {
        $names=  $this->getEntityManager()->createQuery('SELECT distinct(reelCore.name)'
                . ' from ApplicationFrontBundle:ReelCore reelCore'
                )->getScalarResult();
        $reel = array_map("current",$names);

        return $reel;
    }
}
