<?php

namespace Application\Bundle\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReelDiametersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReelDiametersRepository extends EntityRepository
{
    public function getAllAsArray()
    {
        $names = $this->getEntityManager()->createQuery('SELECT distinct(reelDiameters.name)'
                . ' from ApplicationFrontBundle:ReelDiameters reelDiameters'
                )->getScalarResult();
        $rd = array_map("current",$names);

        return $rd;
    }
}
