<?php

namespace Application\Bundle\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SlidesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlidesRepository extends EntityRepository
{
    public function getAllAsArray(){
        $names = $this->getEntityManager()->createQuery('SELECT distinct(slides.name)'
                . ' from ApplicationFrontBundle:Slides slides'
                )->getScalarResult();
        $slides = array_map("current",$names);
        return $slides;
    }
}
