<?php

namespace Application\Bundle\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository
{
    public function getUsersWithoutCurentLoggedIn($id, $organizationId = null)
    {
        $where = ' Where id != '. $id;
        if($organizationId){
            $where .= ' AND organizations = '.$organizationId;
        }
        $query = $this->getEntityManager()->createQuery('SELECT *'
                . ' from ApplicationFrontBundle:Users u '
                . ' '. $where
                );
        $users = $query->getResult();
        return $users;
    }
}
