<?php
/**
 * AVCC
 * 
 * @category AVCC
 * @package  Application
 * @author   Nouman Tayyab <nouman@avpreserve.com>
 * @author   Rimsha Khalid <rimsha@avpreserve.com>
 * @license  AGPLv3 http://www.gnu.org/licenses/agpl-3.0.txt
 * @copyright Audio Visual Preservation Solutions, Inc
 * @link     http://avcc.avpreserve.com
 */
namespace Application\Bundle\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository {

    public function getUsersWithoutCurentLoggedIn($id, $organizationId = null) {
        $where = ' Where u.id != ' . $id;
        if ($organizationId) {
            $where .= ' AND u.organizations = ' . $organizationId;
        }
        $query = $this->getEntityManager()->createQuery('SELECT u'
                . ' from ApplicationFrontBundle:Users u '
                . ' ' . $where
        );
        $users = $query->getResult();
        return $users;
    }
}
